site_name: wireshell
site_url: http://wireshell.pw/
repo_url: https://github.com/wireshell/wireshell
repo_name: Github
site_description: A command-line interface for CMS/CMF ProcessWire based on Symfony Console component. Can be easily extended through ProcessWire's ability of being bootstrapped into other applications, its great API and Symfony Console's modular command approach.
site_favicon: favicon.ico
pages:
- ['index.md', 'Introduction']
theme: slate
