site_name: wireshell docs
site_author: ""
site_url: http://wireshell.pw/
repo_url: https://github.com/wireshell/wireshell
repo_name: wireshell
repo_name: Github
site_description: A command-line interface for CMS/CMF ProcessWire based on Symfony Console component. Can be easily extended through ProcessWire's ability of being bootstrapped into other applications, its great API and Symfony Console's modular command approach.
site_favicon: favicon.ico
theme: readthedocs
# extra_javascript:
extra_css: 
  - assets/css/extra.css
markdown_extensions:
  - extra
include_search: true
pages:
- Home: index.md
- General:
  - Installation: install.md
  - Updating: updating.md
  - Extending: extending.md
  - Changelog: changelog.md
- Commands:
  - Common: commands/common.md
  - Template: commands/template.md
  - Page: commands/page.md
  - Field: commands/field.md
  - Module: commands/module.md
  - User: commands/user.md
  - Role: commands/role.md
  - Backup: commands/backup.md
- About: 
  - FAQ: faq.md
  - Licence: licence.md
  - Contributors: contributors.md
  - Code Of Conduct: code.md
  - Support: support.md
